### ISSUE TITLE
Finished WUs Won't Send

### ISSUE THREAD

**Issue by buckit-head** [FoldingAtHome/fah-issues#1438]
A few work units will not send after they have been completed. My internet connection is working fine, and some WUs will be sent upon completion. Certain ones just wont go, even after a day or two.

I'm not very savvy at this stuff, but I searched the log and came across this:

> 17:16:55:WARNING:WU01:FS01:Exception: Failed to send results to work server: Transfer failed
17:16:55:WU01:FS01:Trying to send results to collection server
17:16:55:WU01:FS01:Uploading 141.53MiB to 3.21.157.11
17:16:55:WU01:FS01:Connecting to 3.21.157.11:8080
17:16:55:ERROR:WU01:FS01:Exception: Transfer failed

**Comment by bb30994** [comment]
This is what happens when a WU exceeds the maximum size allowed by the receiving server.  Apparently the server was limited to 100MiB.  That setting has been corrected on the server in question.

**Comment by PantherX** [comment]
Please note that since the issue was resolved on the Server, I will be closing this issue.

In future, if you have any issues, please hop over the the Official Forum: https://foldingforum.org/index.php for troubleshooting. We prefer to use GitHub to document reproducible issues to fix by the development team. If in doubt, it's better to first post in the Forum and if it is confirmed to be an issue, one will be created.

**Comment by bb30994** [comment]
Solving the problem on one server doesn't resolve it on other servers.  https://foldingforum.org/viewtopic.php?f=18&t=36138
Either we need to convince each project owner to set a limit that works for their project or we need to remove the cap.  If we do that, we'll also need to do a better job of deciding when the data stream had been interrupted.
