### ISSUE TITLE
Dependency on Python 2.x.x causes error installing in some Linux systems

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-issues#858]
| Trac | Data |
| --: | :-- |
| Ticket | 858 |
| Reported by | @7im- |
| Status | accepted |
| Component | RPM Package |
| Priority | 4 |
| Keywords | python fedora install requirement dependency |

Installing FAHControl on a fresh, udpated Fedora 16 VM.  

Transaction error, requires Python 2.6.  See picture.

**Comment by 2E0PGS** [comment]
I still get this for the FAH Control on Ubuntu. I also get this on Manjaro but I can recomile it on the fly to work around it.

**Comment by bb30994** [comment]
This has become URGENT inasmuch as python2 is due to officially be retired in less than a month.
> It's had a good innings, but relying on ancient languages was bound to bite sooner or later.
>
> Python3 has been around for 11 years and python2 is heading to the grave next year.

See https://pythonclock.org

**Comment by dmc5179** [comment]
I am able to run the FAHClient on Ubuntu 18.04 but do have to install python2

**Comment by lightningjim** [comment]
I'm running Ubuntu 20.04 and while I was able to install python2 (doesn't come by default from now on) FAHControl relies on dependencies that have since been pulled from OS repositories

fahcontrol : Depends: python-gtk2 but it is not installable or
                       python-gnome2 but it is not installable

**Comment by brealorg** [comment]
> I'm running Ubuntu 20.04 and while I was able to install python2 (doesn't come by default from now on) FAHControl relies on dependencies that have since been pulled from OS repositories
> 
> fahcontrol : Depends: python-gtk2 but it is not installable or
> python-gnome2 but it is not installable
Can confirm. 
Neither beta-release is fixing this issue or the quickfix:

```
ar x fahcontrol_7.5.1-1_all.deb
tar xf control.tar.gz
sed -i 's/7.5.1-1/7.5.1-2/g' control
sed -i 's/python-gnome2/python-gtk2/g' control
rm control.tar.gz
tar cf control.tar.gz control md5sums
ar rcs fahcontrol_7.5.1-2_all.deb debian-binary control.tar.gz data.tar.xz
sudo dpkg -i fahcontrol_7.5.1-2_all.deb

```

**Comment by rakvium** [comment]
@brealorg, @lightningjim, beta version 7.6.13-1_all works well for me on Ubuntu 20.04 right now.
You can download it here: https://foldingathome.org/beta/ and use it before the fix is available in the stable version.

**Comment by lightningjim** [comment]
@rakvium Still having the same problems

$ sudo apt install ./fahcontrol_7.6.13-1_all.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'fahcontrol' instead of './fahcontrol_7.6.13-1_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 fahcontrol : Depends: python-gtk2 but it is not installable or
                       python-gnome2 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by shorttack** [comment]
@rakvium Acknowledged. Please follow this issue at the foldingforum.org support community. Many have this working now using the software package manager instead of apt.

**Comment by rakvium** [comment]
@lightningjim sorry, it looks like I have python-gtk2 installed.

**Comment by bb30994** [comment]
somebody needs to rename the current software ***-python2** and built a current version for python3 which is supported in newer distros.

**Comment by ffissore** [comment]
There's an open pull request with the porting of fah-control from python2 to python3 https://github.com/FoldingAtHome/fah-control/pull/70. Please use that and give back your feedback
